deltaFlow: ArgumentParser Class Reference
ArgumentParser Class Reference final
Parses and stores command-line arguments for deltaFlow.
#include <Argparse.H>
Public Member Functions
ArgumentParser (int argc, char *argv[])
Constructor: parses command-line arguments.
~ArgumentParser ()=default
Destructor (default).
ArgumentParser (const ArgumentParser &)=delete
ArgumentParser & operator= (const ArgumentParser &)=delete
ArgumentParser (const ArgumentParser &&)=delete
ArgumentParser & operator= (ArgumentParser &&)=delete
std::string getBusDataCsv () const noexcept
Get the bus data CSV file name.
std::string getBranchDataCsv () const noexcept
Get the branch data CSV file name.
double getTolerance () const noexcept
Get the convergence tolerance ($$ \epsilon $$).
int getMaxIterations () const noexcept
Get the maximum number of iterations ($$ N_{max} $$).
double getRelaxationCoefficient () const noexcept
Get the relaxation coefficient ($$ \omega $$).
Solver getSolver () const noexcept
Get the solver type.
Private Member Functions
void parse_args (int argc, char *argv[])
Parse the provided arguments.
void help () const noexcept
Print help message to stdout.
void version () const noexcept
Print version information to stdout.
Private Attributes
std::string busDataCsv
Path to bus data CSV file.
std::string branchDataCsv
Path to branch data CSV file.
double tolerance = 1E-8
Convergence tolerance ($$ \epsilon $$)
int maxIterations = 1024
Maximum number of iterations ($$ N_{max} $$)
double relaxation = 1.0
Relaxation coefficient ($$ \omega $$)
Solver method
Solver type.
Detailed Description
Parses and stores command-line arguments for deltaFlow.
The ArgumentParser extracts command-line arguments related to bus/branch data files, solver selection, convergence tolerance ($$ \epsilon $$), maximum iterations ($$ N_{max} $$), and relaxation coefficient ($$ \omega $$).
Definition at line 54 of file Argparse.H.
Constructor & Destructor Documentation
ArgumentParser() [1/3]
ArgumentParser::ArgumentParser (int argc, char * argv[])
Constructor: parses command-line arguments.
Parameters
argc Argument count.
argv Argument vector.
Definition at line 10 of file Argparse.C.
{
    parse_args(argc, argv);
}
References parse_args().
~ArgumentParser()
ArgumentParser::~ArgumentParser () default
Destructor (default).
ArgumentParser() [2/3]
ArgumentParser::ArgumentParser (const ArgumentParser &) delete
ArgumentParser() [3/3]
ArgumentParser::ArgumentParser (const ArgumentParser &&) delete
Member Function Documentation
getBranchDataCsv()
std::string ArgumentParser::getBranchDataCsv () const noexcept
Get the branch data CSV file name.
Returns
File path as std::string.
Definition at line 88 of file Argparse.C.
{
    return this->branchDataCsv;
}
References branchDataCsv.
getBusDataCsv()
std::string ArgumentParser::getBusDataCsv () const noexcept
Get the bus data CSV file name.
Returns
File path as std::string.
Definition at line 84 of file Argparse.C.
{
    return this->busDataCsv;
}
References busDataCsv.
getMaxIterations()
int ArgumentParser::getMaxIterations () const noexcept
Get the maximum number of iterations ($$ N_{max} $$).
Returns
Maximum iterations as int.
Definition at line 96 of file Argparse.C.
{
    return this->maxIterations;
}
References maxIterations.
getRelaxationCoefficient()
double ArgumentParser::getRelaxationCoefficient () const noexcept
Get the relaxation coefficient ($$ \omega $$).
Returns
Relaxation coefficient as double.
Definition at line 100 of file Argparse.C.
{
    return this->relaxation;
}
References relaxation.
getSolver()
Solver ArgumentParser::getSolver () const noexcept
Get the solver type.
Returns
Solver enum (GaussSeidel or NewtonRaphson).
Definition at line 104 of file Argparse.C.
{
    return this->method;
}
References method.
getTolerance()
double ArgumentParser::getTolerance () const noexcept
Get the convergence tolerance ($$ \epsilon $$).
Returns
Tolerance as double.
Definition at line 92 of file Argparse.C.
{
    return this->tolerance;
}
References tolerance.
help()
void ArgumentParser::help () const private noexcept
Print help message to stdout.
Definition at line 108 of file Argparse.C.
{
    MESSAGE(R"(
Usage:
  deltaFlow [OPTIONS] <method>
Required:
  -b, --bus <file>             Path to Bus Data CSV file
  -l, --branch <file>          Path to Branch Data CSV file
  <solver>                     Solver method: gauss-seidel | newton-raphson
Options:
  -t, --tolerance <value>      Convergence tolerance (default: 1E-8)
  -m, --max-iterations <int>   Maximum number of iterations (default: 1024)
  -r, --relaxation <value>     Relaxation coefficient (only for gauss-seidel, default: 1.0)
  -h, --help                   Display this help message and exit
  -v, --version                Show program version and exit
Solvers:
  gauss-seidel                Iterative method suitable for smaller systems. Supports relaxation.
  newton-raphson              Robust method for large or nonlinear systems. Typically converges faster,
                              but requires more computation per iteration.
)");
}
References MESSAGE.
operator=() [1/2]
ArgumentParser & ArgumentParser::operator= (ArgumentParser &&) delete
operator=() [2/2]
ArgumentParser & ArgumentParser::operator= (const ArgumentParser &) delete
parse_args()
void ArgumentParser::parse_args (int argc, char * argv[]) private
Parse the provided arguments.
Parameters
argc Argument count.
argv Argument vector.
Definition at line 14 of file Argparse.C.
{
    bool methodFound = false;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "--bus" || arg == "-b") && i + 1 < argc) {
            this->busDataCsv = argv[++i];
        }
        else if ((arg == "--line" || arg == "-l") && i + 1 < argc) {
            this->branchDataCsv = argv[++i];
        }
        else if ((arg == "--tolerance" || arg == "-t") && i + 1 < argc) {
            this->tolerance = std::stod(argv[++i]);
        }
        else if ((arg == "--max-iterations" || arg == "-m") && i + 1 < argc) {
            this->maxIterations = std::stoi(argv[++i]);
        }
        else if ((arg == "--relaxation" || arg == "-r") && i + 1 < argc) {
            this->relaxation = std::stod(argv[++i]);
        }
        else if (arg == "--version" || arg == "-v") {
            version();
            std::exit(0);
        }
        else if (arg == "--help" || arg == "-h") {
            help();
            std::exit(0);
        }
        else if (!methodFound) {
            if (arg == "gauss-seidel") {
                this->method = Solver::GaussSeidel;
                methodFound = true;
            }
            else if (arg == "newton-raphson") {
                this->method = Solver::NewtonRaphson;
                methodFound = true;
            }
            else {
                MESSAGE("ERROR: Invalid method '{}'", arg);
                help();
                std::exit(1);
            }
        }
        else {
            MESSAGE("ERROR: Unexpected extra argument '{}'", arg);
            help();
            std::exit(1);
        }
    }
    if (!(Utilities::endswith(busDataCsv, ".csv") && Utilities::endswith(branchDataCsv, ".csv"))) {
        MESSAGE("ERROR: Bus & branch data csv file is required.");
        help();
        std::exit(1);
    }
    if (!methodFound) {
        MESSAGE("ERROR: Missing required method argument (gauss-seidel or newton-raphson).");
        help();
        std::exit(1);
    }
    if (method == Solver::NewtonRaphson && relaxation != 1.0) {
        MESSAGE("Warning: Relaxation coefficient ignored for method 'newton-raphson'");
    }
    DEBUG("deltaFlow v{}", deltaFlow_VERSION);
}
References branchDataCsv, busDataCsv, DEBUG, Utilities::endswith(), GaussSeidel, help(), maxIterations, MESSAGE, method, NewtonRaphson, relaxation, tolerance, and version().
version()
void ArgumentParser::version () const private noexcept
Print version information to stdout.
Definition at line 132 of file Argparse.C.
{
    MESSAGE("deltaFlow v{}", deltaFlow_VERSION);
}
References MESSAGE.
Member Data Documentation
branchDataCsv
std::string ArgumentParser::branchDataCsv private
Path to branch data CSV file.
Definition at line 112 of file Argparse.H.
busDataCsv
std::string ArgumentParser::busDataCsv private
Path to bus data CSV file.
Definition at line 111 of file Argparse.H.
maxIterations
int ArgumentParser::maxIterations = 1024 private
Maximum number of iterations ($$ N_{max} $$)
Definition at line 114 of file Argparse.H.
method
Solver ArgumentParser::method private
Solver type.
Definition at line 116 of file Argparse.H.
relaxation
double ArgumentParser::relaxation = 1.0 private
Relaxation coefficient ($$ \omega $$)
Definition at line 115 of file Argparse.H.
tolerance
double ArgumentParser::tolerance = 1E-8 private
Convergence tolerance ($$ \epsilon $$)
Definition at line 113 of file Argparse.H.
The documentation for this class was generated from the following files:
src/utilities/Argparse.H
src/utilities/Argparse.C