#include "algorithms.H"

void GAUSS_SEIDEL(DOUBLE_COMPLEX *V, DOUBLE *P, DOUBLE *Q, DOUBLE_COMPLEX *Y, INTEGER *N, INTEGER *MAXITER, DOUBLE *TOL) {
    API_GAUSS_SEIDEL(V, P, Q, Y, N, MAXITER, TOL);
}

void NEWTON_RAPHSON(DOUBLE_COMPLEX *V, DOUBLE *P, DOUBLE *Q, DOUBLE_COMPLEX *Y, INTEGER *N, INTEGER *MAXITER, DOUBLE *TOL) {
    API_NEWTON_RAPHSON(V, P, Q, Y, N, MAXITER, TOL);
}
