macro(REGISTER_GLOBAL_SOURCES_AND_INCLUDES VARIABLE_SOURCES VARIABLE_INCLUDES)
    file(GLOB SOURCES *.C)

    get_property(CURRENT_SOURCES GLOBAL PROPERTY ${VARIABLE_SOURCES})
    set_property(GLOBAL PROPERTY ${VARIABLE_SOURCES} "${CURRENT_SOURCES}" "${SOURCES}")

    set(INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR};${CMAKE_CURRENT_BINARY_DIR}")

    get_property(CURRENT_INCLUDES GLOBAL PROPERTY ${VARIABLE_INCLUDES})
    set_property(GLOBAL PROPERTY ${VARIABLE_INCLUDES} "${CURRENT_INCLUDES}" "${INCLUDE_DIRS}")
endmacro()
